# Generated by Django 4.2.7 on 2023-12-24 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='UUID',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 3, 55, 57, 329529, tzinfo=datetime.timezone.utc)),
        ),
    ]
