# Generated by Django 4.2.6 on 2024-05-16 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 11, 38, 12, 114861, tzinfo=datetime.timezone.utc)),
        ),
    ]
