# Generated by Django 4.2.6 on 2023-11-14 02:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 2, 42, 43, 927561, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='StudentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=40, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('studentsession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.studentsession')),
            ],
        ),
    ]
