# Generated by Django 4.2.6 on 2023-11-16 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 15, 52, 17, 644123, tzinfo=datetime.timezone.utc)),
        ),
    ]
