# Generated by Django 4.2.6 on 2024-03-27 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 10, 58, 55, 32823, tzinfo=datetime.timezone.utc)),
        ),
    ]
