# Generated by Django 4.2.7 on 2023-12-25 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 1, 41, 31, 74600, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='UUID',
            field=models.CharField(blank=True, max_length=38, null=True, unique=True),
        ),
    ]
