# Generated by Django 4.2.7 on 2023-12-25 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_student_uuid_alter_session_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='UUID_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 1, 11, 33, 871938, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='UUID',
            field=models.CharField(max_length=38, null=True, unique=True),
        ),
    ]
