# Generated by Django 5.0.6 on 2024-07-01 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_session_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 28, 18, 278416, tzinfo=datetime.timezone.utc)),
        ),
    ]
