# Generated by Django 4.2.6 on 2024-02-09 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_course_code_alter_session_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 1, 30, 11, 229880, tzinfo=datetime.timezone.utc)),
        ),
    ]
