# Generated by Django 4.2.6 on 2024-05-18 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_session_expiration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsession',
            name='attended',
        ),
        migrations.AddField(
            model_name='studentsession',
            name='attended_end',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='attended_start',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 1, 4, 30, 569363, tzinfo=datetime.timezone.utc)),
        ),
    ]
