# Generated by Django 4.2.6 on 2024-05-13 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_session_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 11, 16, 55, 665986, tzinfo=datetime.timezone.utc)),
        ),
    ]
