# Generated by Django 4.2.7 on 2023-12-25 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_session_expiration_time_alter_student_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 1, 48, 47, 875969, tzinfo=datetime.timezone.utc)),
        ),
    ]
