# Generated by Django 4.2.6 on 2023-11-15 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_session_expiration_time_studentpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpermission',
            name='status',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 19, 47, 27, 702197, tzinfo=datetime.timezone.utc)),
        ),
    ]
