# Generated by Django 4.2.6 on 2024-05-06 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_session_expiration_time_studenttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 4, 1, 32, 598044, tzinfo=datetime.timezone.utc)),
        ),
    ]
