# Generated by Django 4.2.6 on 2023-11-15 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_studentpermission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 19, 50, 47, 666644, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentpermission',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
