# Generated by Django 4.2.6 on 2024-05-18 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_studentsession_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='attended',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 1, 14, 46, 458307, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='attended_end',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='attended_start',
            field=models.BooleanField(null=True),
        ),
    ]
