# Generated by Django 4.2.6 on 2023-11-15 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_session_expiration_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpermission',
            name='dstrike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 23, 47, 8, 723293, tzinfo=datetime.timezone.utc)),
        ),
    ]
