# Generated by Django 4.2.6 on 2024-05-18 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_studentsession_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 1, 51, 48, 231672, tzinfo=datetime.timezone.utc)),
        ),
    ]
