# Generated by Django 4.2.6 on 2023-10-25 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_glocation_alter_session_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 2, 29, 50, 793257, tzinfo=datetime.timezone.utc)),
        ),
    ]
