# Generated by Django 4.2.6 on 2024-05-18 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_session_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 2, 8, 4, 387203, tzinfo=datetime.timezone.utc)),
        ),
    ]
