# Generated by Django 4.2.6 on 2023-11-16 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_studentpermission_dstrike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpermission',
            name='dstrike',
        ),
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 2, 38, 40, 585222, tzinfo=datetime.timezone.utc)),
        ),
    ]
