# Generated by Django 4.2.6 on 2023-10-21 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_session_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 14, 5, 18, 564731, tzinfo=datetime.timezone.utc)),
        ),
    ]
