# Generated by Django 4.2.6 on 2024-05-07 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_session_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 23, 34, 41, 561824, tzinfo=datetime.timezone.utc)),
        ),
    ]
