# Generated by Django 4.2.6 on 2023-10-25 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_session_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attended_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attended_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 4, 23, 25, 288219, tzinfo=datetime.timezone.utc)),
        ),
    ]
