# Generated by Django 4.2.6 on 2024-05-11 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_session_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 21, 6, 34, 40721, tzinfo=datetime.timezone.utc)),
        ),
    ]
