# Generated by Django 4.2.6 on 2024-05-13 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_session_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 2, 21, 48, 754336, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expiration_time',
            field=models.PositiveIntegerField(),
        ),
    ]
