# Generated by Django 4.2.6 on 2023-10-25 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_attendance_attended_end_attendance_attended_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 4, 25, 15, 661425, tzinfo=datetime.timezone.utc)),
        ),
    ]
