# Generated by Django 4.2.6 on 2024-05-13 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_session_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 2, 28, 43, 320012, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expiration_time',
            field=models.DateTimeField(),
        ),
    ]
